### ISSUE TITLE
`node-pre-gyp` expects `/releases`

### ISSUE THREAD

**Issue by brian6932** [xiBread/inspect-promise#7]
AKA artifacts need to be published
```
❯ pnpm i inspect-promise
Packages: +40
++++++++++++++++++++++++++++++++++++++++
Progress: resolved 134, reused 134, downloaded 0, added 0, done
node_modules/.pnpm/inspect-promise@2.0.5/node_modules/inspect-promise: Running install script, failed in 1.9s
.../node_modules/inspect-promise install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@21.6.2 | win32 | x64
│ (node:6916) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promise@2.0.5\node_modules\inspect-promise\prebuild\inspectPromise-node-v120-win32-x64-unknown-{libc_version}\inspectPromise.node" (not found)
│ node-pre-gyp http GET https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
│ node-pre-gyp WARN Pre-built binaries not installable for inspect-promise@2.0.5 and node@21.6.2 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
```

**Comment by olivermrose** [comment]
Whoops, forgot to release after everything. Although, it should've fallen back to build 🤔

**Comment by olivermrose** [comment]
OK, release published. I'll keep this open just in case (also, I appreciate your patience with this whole process, cross-compilation is a nightmare with C++).

**Comment by brian6932** [comment]
Seems like it specifically looks for `{libc_version}` (URI encoded as `%7Blibc_version%7D`), currently running the command returns the same error.

> Although, it should've fallen back to build

Yea it does, but for some reason now that the bins were added, pnpm uses the wrong version of `node-gyp` for me, even though I specifically installed `10.0.1` in my `node_modules`, not sure what changed, but before it was able to detect it. [The older `node-gyp` version isn't compatible with my python version.](https://github.com/nodejs/node-gyp/issues/2869)

> cross-compilation is a nightmare with C++

ye true😅

**Comment by olivermrose** [comment]
> `{libc_version}`

Apparently this variable was deprecated and the docs haven't been updated, fun.

> pnpm uses the wrong version of node-gyp

I ran into the same problem with pnpm which is why I ended up switching to yarn. I don't think I can do anything about that as I'm pretty sure that's related to pnpm's resolution strategy.

**Comment by brian6932** [comment]
It's weird, it worked here for me https://github.com/xiBread/inspect-promise/issues/3#issue-2168091746 I installed it specifically within the package.json, but it no longer works 🤷.

Currently
```
❯ pnpm i inspect-promise
Packages: +40
++++++++++++++++++++++++++++++++++++++++
Progress: resolved 134, reused 134, downloaded 0, added 0, done
node_modules/.pnpm/inspect-promise@2.0.5/node_modules/inspect-promise: Running install script, failed in 1.8s
.../node_modules/inspect-promise install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.11
│ node-pre-gyp info using node@21.6.2 | win32 | x64
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp info check checked for "~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promise@2.0.5\node_modules\inspect-promise\prebuild\inspectPromise-node-v120-win32-x64-unknown-{libc_version}\inspectPromise.node" (not found)
│ node-pre-gyp http GET https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
│ node-pre-gyp ERR! install response status 404 Not Found on https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
│ node-pre-gyp WARN Pre-built binaries not installable for inspect-promise@2.0.5 and node@21.6.2 (node-v120 ABI, unknown) (falling back to source compile with node-gyp)
│ node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/xiBread/inspect-promise/releases/download/v2.0.5/inspectPromise-v2.0.5-node-v120-win32-x64-unknown-%7Blibc_version%7D.tar.gz
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@21.6.2 | win32 | x64
│ gyp info ok
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.4.1
│ gyp info using node@21.6.2 | win32 | x64
│ gyp info find Python using Python version 3.12.2 found at "~\scoop\apps\python\current\python.exe"
│ gyp info find VS using VS2022 (17.9.34622.214) found at:
│ gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
│ gyp info find VS run with --verbose for detailed information
│ gyp info spawn ~\scoop\apps\python\current\python.exe
│ gyp info spawn args [
│ gyp info spawn args   '~\\AppData\\Local\\node\\corepack\\pnpm\\8.15.4\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'msvs',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '~\\Documents\\GitHub\\repo\\node_modules\\.pnpm\\inspect-promise@2.0.5\\node_modules\\inspect-promise\\build\\config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '~\\AppData\\Local\\node\\corepack\\pnpm\\8.15.4\\dist\\node_modules\\node-gyp\\addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '~\\AppData\\Local\\node-gyp\\Cache\\21.6.2\\include\\node\\common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=~\\AppData\\Local\\node-gyp\\Cache\\21.6.2',
│ gyp info spawn args   '-Dnode_gyp_dir=~\\AppData\\Local\\node\\corepack\\pnpm\\8.15.4\\dist\\node_modules\\node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=~\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.6.2\\\\<(target_arch)\\\\node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=~\\Documents\\GitHub\\repo\\node_modules\\.pnpm\\inspect-promise@2.0.5\\node_modules\\inspect-promise',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   '~\\Documents\\GitHub\\repo\\node_modules\\.pnpm\\inspect-promise@2.0.5\\node_modules\\inspect-promise\\build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Traceback (most recent call last):
│   File "~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
│     import gyp  # noqa: E402
│     ^^^^^^^^^^
│   File "~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
│     import gyp.input
│   File "~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
│     from distutils.version import StrictVersion
│ ModuleNotFoundError: No module named 'distutils'
│ gyp ERR! configure error
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\lib\configure.js:325:16)
│ gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
│ gyp ERR! System Windows_NT 10.0.19044
│ gyp ERR! command "~\\scoop\\apps\\nodejs\\current\\node.exe" "~\\AppData\\Local\\node\\corepack\\pnpm\\8.15.4\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=~\\Documents\\GitHub\\repo\\…
│ gyp ERR! cwd ~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promise@2.0.5\node_modules\inspect-promise
│ gyp ERR! node -v v21.6.2
│ gyp ERR! node-gyp -v v9.4.1
│ gyp ERR! not ok
│ node-pre-gyp ERR! build error
│ node-pre-gyp ERR! stack Error: Failed to execute '~\scoop\apps\nodejs\current\node.exe ~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=~\Documents\GitHub\repo\no…
│ node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (~\Documents\GitHub\repo\node_modules\.pnpm\@mapbox+node-pre-gyp@1.0.11\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
│ node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
│ node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
│ node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
│ node-pre-gyp ERR! System Windows_NT 10.0.19044
│ node-pre-gyp ERR! command "~\\scoop\\apps\\nodejs\\current\\node.exe" "~\\Documents\\GitHub\\repo\\node_modules\\.pnpm\\@mapbox+node-pre-gyp@1.0.11\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
│ node-pre-gyp ERR! cwd ~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promise@2.0.5\node_modules\inspect-promise
│ node-pre-gyp ERR! node -v v21.6.2
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.11
│ node-pre-gyp ERR! not ok
│ Failed to execute '~\scoop\apps\nodejs\current\node.exe ~\AppData\Local\node\corepack\pnpm\8.15.4\dist\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promis…
```

**Comment by brian6932** [comment]
Ok getting this now 🤔
```
❯ pnpm i inspect-promise
Packages: +40
++++++++++++++++++++++++++++++++++++++++
Progress: resolved 134, reused 133, downloaded 1, added 1, done
node_modules/.pnpm/inspect-promise@2.0.6/node_modules/inspect-promise: Running install script, done in 821ms

dependencies:
+ inspect-promise 2.0.6

Done in 2.7s

❯ node
Welcome to Node.js v21.6.2.
Type ".help" for more information.
> {inspectPromise} = await import(`inspect-promise`)
Uncaught:
Error: The module '\\?\~\Documents\GitHub\repo\node_modules\.pnpm\inspect-promise@2.0.6\node_modules\inspect-promise\prebuild\inspectPromise-win32-x64\inspectPromise.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 120. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1475:18)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by olivermrose** [comment]
Guess I need the node abi in the name after all... Also, I think https://github.com/pnpm/pnpm/issues/4347 might be related to the pnpm issue? Though, I tried the workaround and it didn't seem to change anything.

**Comment by brian6932** [comment]
Fixed
```
❯ node
Welcome to Node.js v21.6.2.
Type ".help" for more information.
> {inspectPromise} = await import(`inspect-promise`)
[Module: null prototype] {
  __esModule: true,
  default: {
    inspectPromise: [Function: inspectPromise],
    default: [Function: inspectPromise]
  },
  inspectPromise: [Function: inspectPromise]
}
> inspectPromise(new Promise(() => {}))
{ state: 'pending', value: undefined }
>
```
